create table tb_event (id  bigserial not null, address varchar(255), date timestamp, description varchar(255), image_uri varchar(255), latitude float8, longitude float8, name varchar(255), price float8, status int4, tickets int8, primary key (id));
create table tb_order (id  bigserial not null, moment timestamp, qtd int4, status int4, total float8, user_id int8, primary key (id));
create table tb_order_event (order_id int8 not null, event_id int8 not null, primary key (order_id, event_id));
create table tb_user (id  bigserial not null, cpf varchar(255), email varchar(255), name varchar(255), pass varchar(255), status int4, primary key (id));
create table tb_user_history (user_id int8 not null, event_id int8 not null, primary key (user_id, event_id));
alter table if exists tb_user_history add constraint UK_cd1rmd2argx0xrmgp7be8rrvl unique (event_id);
alter table if exists tb_order_event add constraint FK275vl57ibx7yw5d3rr0ym71hm foreign key (event_id) references tb_event;
alter table if exists tb_order_event add constraint FK67uejshkqrcaqn67gjqmqmm foreign key (order_id) references tb_order;
alter table if exists tb_user_history add constraint FKtp2po8bxsfljnyt51rkug5hwj foreign key (event_id) references tb_event;
alter table if exists tb_user_history add constraint FKrde89thx2r5wyw87hk2fqud5n foreign key (user_id) references tb_user;
